version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./mab_web_app/logs:/app/mab_web_app/logs
      - ./mab_web_app/data:/app/mab_web_app/data
      - ./mab_web_app/static/images:/app/mab_web_app/static/images
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 